### ISSUE TITLE
Submit to Packages?

### ISSUE THREAD

**Issue by Naatan** [k-barton/komodor#1]
I'm sure many people would love to take this for a spin :) Great work! 

Instructions: http://komodoide.com/packages/submit-instructions/#pane-packages

**Comment by k-barton** [comment]
yes, that's the plan. But I want to fix a few things before publishing it (and getting flooded over with user's bug reports...).

**Comment by Naatan** [comment]
Great, I look forward to it :)

Fair warning - Komodo 9.3 will have built-in support for R, but only syntax highlighting, so your addon is still very much relevant. You may want to do some tweaking for 9.3 though. The first nightly should be out by next week.

**Comment by k-barton** [comment]
Is that the scintilla's default R lexer? It seems to be a slightly modified C lexer and doesn't support some of R's peculiarities.

**Comment by Naatan** [comment]
I believe so. @mitchell-as you may wanna have a look at this.

We're not R programmers ourselves so we rely on those who are proficient in that language to point things like this out (nightlies are perfect for that). Appreciate any help you can give us :) Again though, our intend at the moment is only for basic support, but we very much welcome an addon such as this one to provide advanced support for those who need it.

**Comment by mitchell-as** [comment]
We actually wrote our own lexer instead of using Scintilla's stock lexer, but I'm sure it will have its own quirks that you can help us iron out :)

**Comment by k-barton** [comment]
I'll be glad to help. For instance (which was a bit of a pain to do with Luddite), in `function(arg1, arg2, arg3)` and `foo(arg1=, arg2=, arg3=)` the __arg__*s should be coloured differently than in `foo(arg1, arg2, arg3)`.

**Comment by Naatan** [comment]
Do you mean to imply there is a value after the `=` or is that some type of denotation in R?

**Comment by k-barton** [comment]
Function definition syntax:
`function(argname1, argname2=EXPR) `
where argument values are optional, but unlike in function call empty argument value after "=" is not allowed, so
`function(argname1=) ` is __wrong__.

Function call syntax:
`foo(argvalue, argname2=EXPR, argname3=)`
where argument names are optional, and named argument's value after "=" is optional. 

`EXPR` is any R expression (also including nested brackets of all kinds)

**Comment by Naatan** [comment]
Ok, that's pretty similar to Python, JS, PHP, ... and for none of those do we color those types of arguments differently. I don't think it would make sense for us to start doing so now unless we also do it for those other languages (which may very well be feasible, but that's a task on it's own rather than for this language specifically).

**Comment by k-barton** [comment]
So what happens if an addon installs a lexer for language that is already built in? I don't think there is a way for user to select a preferred lexer, or is there?

**Comment by Naatan** [comment]
I believe the best solution would be to have language names that slightly differ, and allow the user to set their preferred language via file associations. @mitchell-as can you confirm?

**Comment by mitchell-as** [comment]
I confirm. There's some language registration going on behind the scenes and any overwrites will not save the original, so it couldn't be a preference anyway.
