### ISSUE TITLE
Komodo Edit: R Interface

### ISSUE THREAD

**Issue by carabidus** [k-barton/komodor#11]
I recently installed the `R Interface` package for Komodo Edit. Everything seems perfectly normal from the Komodo side: Rterm window appears, test connection a "success", etc... However, I get the following error in the Rterm window when I try to run a simple test, `rnorm(5)`, from the scripting window:

`Error in assign("last.warning", last.warning, envir = baseenv()) :
cannot change value of locked binding for 'last.warning'`

I can input/output R code successfully in the Rterm window, but of course, that defeats the purpose of Komodo entirely.

Here's the [full error output](https://gist.github.com/carabidus/75b1675d4a55e42234772fe172c678c1).

Any suggestions?

**Comment by k-barton** [comment]
Interesting. `last.warning` should not be locked by default. Which R version you use? You can check with the current release `0.3.52b` if this error persists.

**Comment by carabidus** [comment]
I've tried the most recent versions of MRO (3.4.3) and R (3.4.4). Both give the same result.

**Comment by k-barton** [comment]
Did you try the updated "R Interface" (`0.3.52b`)?

**Comment by carabidus** [comment]
The [link](https://github.com/k-barton/komodor/releases/download/0.3.45b/komodor-0.3.45b-ko.xpi) the package seems to be down.

**Comment by carabidus** [comment]
That did it! Both MRO and "regular" R work with the package now. I really appreciate you taking the time to help me out with my questions. I'm attempting to transition from Rstudio to Komodo for stability reasons. About code completion for the new `R Interface` package: the API catalog for `R_extended` does not show up under `Code Intelligence` options. Is this a separate file that I need to install?

**Comment by k-barton** [comment]
There is no API catalogue as such for R. The completions (at least currently) are retrieved from R environment - you get pretty much the same result as the completion in R Gui (in fact is uses the same routines, with some enhancements).
I've never used MRO, it is good to know that "komodor" works with it as well.
